/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Recommendation = IDL.Variant({
  'reject' : IDL.Null,
  'accept' : IDL.Null,
  'borderline' : IDL.Null,
  'strongReject' : IDL.Null,
  'strongAccept' : IDL.Null,
  'weakReject' : IDL.Null,
  'weakAccept' : IDL.Null,
});
export const PaperResult = IDL.Record({
  'id' : IDL.Text,
  'weakSections' : IDL.Vec(IDL.Text),
  'weaknesses' : IDL.Vec(IDL.Text),
  'acceptanceProbability' : IDL.Nat16,
  'overallScore' : IDL.Nat16,
  'rawReport' : IDL.Text,
  'strengths' : IDL.Vec(IDL.Text),
  'citationScore' : IDL.Nat16,
  'suggestedImprovements' : IDL.Vec(IDL.Text),
  'methodologyScore' : IDL.Nat16,
  'clarityScore' : IDL.Nat16,
  'reproducibilityScore' : IDL.Nat16,
  'submittedAt' : Time,
  'noveltyScore' : IDL.Nat16,
  'experimentScore' : IDL.Nat16,
  'researchGaps' : IDL.Vec(IDL.Text),
  'paperId' : IDL.Text,
  'recommendation' : Recommendation,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'pendingReview' : IDL.Null,
  'analyzing' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'uploaded' : IDL.Null,
  'reviewed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Paper = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'filename' : IDL.Text,
  'blobId' : ExternalBlob,
  'uploadedAt' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPaper' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, ExternalBlob], [], []),
  'addPaperResult' : IDL.Func([PaperResult], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPaperResults' : IDL.Func([], [IDL.Vec(PaperResult)], ['query']),
  'getAllPapers' : IDL.Func([], [IDL.Vec(Paper)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaper' : IDL.Func([IDL.Text], [IDL.Opt(Paper)], ['query']),
  'getPaperResult' : IDL.Func([IDL.Text], [IDL.Opt(PaperResult)], ['query']),
  'getPaperResultsForPaper' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaperResult)],
      ['query'],
    ),
  'getPaperStatus' : IDL.Func([IDL.Text], [IDL.Opt(Status)], []),
  'getPapersByStatus' : IDL.Func([Status], [IDL.Vec(Paper)], ['query']),
  'getPapersByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Paper)], ['query']),
  'getStatus' : IDL.Func([IDL.Text], [IDL.Opt(Status)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPaperStatus' : IDL.Func([IDL.Text, Status], [], []),
  'setStatus' : IDL.Func([IDL.Text, Status], [], []),
  'updatePaperStatus' : IDL.Func([IDL.Text, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Recommendation = IDL.Variant({
    'reject' : IDL.Null,
    'accept' : IDL.Null,
    'borderline' : IDL.Null,
    'strongReject' : IDL.Null,
    'strongAccept' : IDL.Null,
    'weakReject' : IDL.Null,
    'weakAccept' : IDL.Null,
  });
  const PaperResult = IDL.Record({
    'id' : IDL.Text,
    'weakSections' : IDL.Vec(IDL.Text),
    'weaknesses' : IDL.Vec(IDL.Text),
    'acceptanceProbability' : IDL.Nat16,
    'overallScore' : IDL.Nat16,
    'rawReport' : IDL.Text,
    'strengths' : IDL.Vec(IDL.Text),
    'citationScore' : IDL.Nat16,
    'suggestedImprovements' : IDL.Vec(IDL.Text),
    'methodologyScore' : IDL.Nat16,
    'clarityScore' : IDL.Nat16,
    'reproducibilityScore' : IDL.Nat16,
    'submittedAt' : Time,
    'noveltyScore' : IDL.Nat16,
    'experimentScore' : IDL.Nat16,
    'researchGaps' : IDL.Vec(IDL.Text),
    'paperId' : IDL.Text,
    'recommendation' : Recommendation,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'pendingReview' : IDL.Null,
    'analyzing' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'uploaded' : IDL.Null,
    'reviewed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Paper = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'filename' : IDL.Text,
    'blobId' : ExternalBlob,
    'uploadedAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPaper' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, ExternalBlob], [], []),
    'addPaperResult' : IDL.Func([PaperResult], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPaperResults' : IDL.Func([], [IDL.Vec(PaperResult)], ['query']),
    'getAllPapers' : IDL.Func([], [IDL.Vec(Paper)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaper' : IDL.Func([IDL.Text], [IDL.Opt(Paper)], ['query']),
    'getPaperResult' : IDL.Func([IDL.Text], [IDL.Opt(PaperResult)], ['query']),
    'getPaperResultsForPaper' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaperResult)],
        ['query'],
      ),
    'getPaperStatus' : IDL.Func([IDL.Text], [IDL.Opt(Status)], []),
    'getPapersByStatus' : IDL.Func([Status], [IDL.Vec(Paper)], ['query']),
    'getPapersByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Paper)], ['query']),
    'getStatus' : IDL.Func([IDL.Text], [IDL.Opt(Status)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPaperStatus' : IDL.Func([IDL.Text, Status], [], []),
    'setStatus' : IDL.Func([IDL.Text, Status], [], []),
    'updatePaperStatus' : IDL.Func([IDL.Text, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };