/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Paper {
  'id' : string,
  'status' : Status,
  'title' : string,
  'userId' : Principal,
  'filename' : string,
  'blobId' : ExternalBlob,
  'uploadedAt' : Time,
}
export interface PaperResult {
  'id' : string,
  'weakSections' : Array<string>,
  'weaknesses' : Array<string>,
  'acceptanceProbability' : number,
  'overallScore' : number,
  'rawReport' : string,
  'strengths' : Array<string>,
  'citationScore' : number,
  'suggestedImprovements' : Array<string>,
  'methodologyScore' : number,
  'clarityScore' : number,
  'reproducibilityScore' : number,
  'submittedAt' : Time,
  'noveltyScore' : number,
  'experimentScore' : number,
  'researchGaps' : Array<string>,
  'paperId' : string,
  'recommendation' : Recommendation,
}
export type Recommendation = { 'reject' : null } |
  { 'accept' : null } |
  { 'borderline' : null } |
  { 'strongReject' : null } |
  { 'strongAccept' : null } |
  { 'weakReject' : null } |
  { 'weakAccept' : null };
export type Status = { 'pendingReview' : null } |
  { 'analyzing' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'uploaded' : null } |
  { 'reviewed' : null } |
  { 'accepted' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPaper' : ActorMethod<[string, string, string, ExternalBlob], undefined>,
  'addPaperResult' : ActorMethod<[PaperResult], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPaperResults' : ActorMethod<[], Array<PaperResult>>,
  'getAllPapers' : ActorMethod<[], Array<Paper>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaper' : ActorMethod<[string], [] | [Paper]>,
  'getPaperResult' : ActorMethod<[string], [] | [PaperResult]>,
  'getPaperResultsForPaper' : ActorMethod<[string], Array<PaperResult>>,
  'getPaperStatus' : ActorMethod<[string], [] | [Status]>,
  'getPapersByStatus' : ActorMethod<[Status], Array<Paper>>,
  'getPapersByUser' : ActorMethod<[Principal], Array<Paper>>,
  'getStatus' : ActorMethod<[string], [] | [Status]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPaperStatus' : ActorMethod<[string, Status], undefined>,
  'setStatus' : ActorMethod<[string, Status], undefined>,
  'updatePaperStatus' : ActorMethod<[string, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];